import streamlit as st
import numpy as np
import pandas as pd

st.title ("Questionnaire à destination des étudiants d’ATOS-UVS")
st.write("Perception des pratiques pédagogiques des professeurs par les étudiants et effets sur leur cursus scolaire.Nous vous convions à apporter des réponses concises à chacune de ces questions.")


st.header('Information Personnelle :')
N,P,NE=st.columns(3)
N.text_input('Nom:')
P.text_input("Prénom:")
NE.text_input("INE:")
N.date_input('Date de Naissance:')
P.text_input('Lieu de Naissance:')
NE.selectbox('Situation Matrimoniale :',('Célibataire','Marié(e)',' Divorcé ','Veuf ou Veuve'))
S,N= st.columns(2)
S.selectbox('Sexe:',("Masculin ","Feminin"))
N.selectbox('Pays:',('Afrique du sud','Algérie','Benin','Burkina Faso','Cap-Vert','Cameroun',"Côte d'Ivoire",'Gambie','Ghana','Guinée','Guinée Bissau','Gabon','Libéria','Mali','Maroc','Mozambie','Niger','Nigeria','Sénégal','Sierra Léone','Togo','Autre'))
D,M,Du= st.columns(3)
D.selectbox('1-Durant cette formation, vous logez:',('En résidence universitaire du CROUS',' Chez vos parents ','Logement en location En colocation','En chambre chez l’habitant ','Chez un autre membre de votre famille','Autre'))
M.multiselect('2- Moyen de mobilité pour rejoindre votre local d étude :',['Voiture personnelle','Transport commun','à pieds','Vélo','Moto'])
Du.number_input('3- Durée et coût journalier du Trajet :')

E,A,= st.columns(2)
E.radio('4- Êtes-vous bousier ?',('Oui','Non'))
A.radio('5- Avez-vous un emploi en dehors des cours pendant l’année universitaire ?',['Oui','Non'])

Si,Q,Au=st.columns(3)
Si.selectbox('6- Si oui, combien d’heures vous prend-t-il par semaine ?',('30h et plus',' 25 à 30h',' 15 à 24h',' 5 à 14h',' Moins de 5h'))
Q.selectbox('7- Quelle est votre principale source de revenus mensuelle ?',('Parents',' Bourse' ,'Travail d’été',' Travail durant les études'))
Au.text_input('Autres,précisez:')
st.header('Votre choix de Formation / de votre Filière, votre Motivation')
st.write('8- Dans vos démarches concernant l’intégration de cette formation, comment vous êtes-vous renseigné ?')
R,D,De = st.columns(3)
R.checkbox('Recherches sur internet')
D.checkbox('Demandé conseil aux amis, à la famille')
D.checkbox("Siège de l’UVS")
R.checkbox('Demandé conseil aux professeurs')
De.checkbox('Cherché aucun renseignement')
st.radio('9- Estimez-vous avoir été suffisamment renseigné ?',('Oui','Non'))
st.multiselect('10- Quelle(s) est(sont) le(s) principale(s) raison(s) vous ayant conduit à vous inscrire à cette formation :',("Elle est proche de votre domicile","Vos amis y vont aussi","Vous avez un projet professionnel précis qui ne peut se concrétiser qu’en allant à cette formation","Pour le plaisir et la satisfaction d’apprendre de nouvelles choses","Par défaut car vous n’avez pas été accepté dans une filière sélective","Par défaut car vous ne saviez pas trop où vous inscrire (n’aviez pas de véritable projet)"))
st.selectbox('11- Donner votre spécialité :',('Calcul Scientifique','Modélisation','Biologie Moléculaire','Big-Data','Robotic','Intelligence artificielle','Machine leanning'))
st.radio('12- Avez-vous hésité avant d’effectuer le choix de cette filière ?',('Oui','Non'))
st.multiselect('13- Pour quelle(s) raison(s) avez-vous choisi cette filière précisément ? choisir de 1 à 3 les principales raisons vous ayant conduit à vous inscrire dans cette filière',("Intérêt pour la discipline enseignée","Projet professionnel précis","Par curiosité","Vous pensez qu’elle vous permettra d’obtenir un meilleur emploi / une meilleure rémunération","Parce que vous réussissez dans cette discipline","Par défaut car vous ne saviez pas dans quelle voie poursuivre","Par défaut, car vous n’avez pas pu intégrer une filière sélective, et cette filière est celle qui s’en rapproche le plus","Cette filière vous a été conseillée par vos professeurs","Vos amis sont également inscrits dans cette filière","Votre famille a insisté pour que vous vous y inscriviez"))
st.write('14- De façon générale, pensez-vous que les enseignements dispensés dans cette filière vous seront utiles :')

Po,Pu,De=st.columns(3)
Po.radio('- Pour obtenir votre licence',['Oui','Non'])
Pu.radio('- Pour obtenir votre master',(("Oui","Non")))
De.radio('- Dans l’exercice de votre futur métier',(['Oui','Non']))
st.selectbox('15- Connaissez-vous la façon dont vos connaissances seront évaluées aux examens dans les différentes disciplines / matières ?',('Oui','Oui mais pas toutes','Non, je ne les connais pas'))
st.selectbox('16 - Vous sentez-vous globalement bien intégré à l’université ?',('Oui tout à fait','Plutôt oui','Plutôt non','Non pas du tout'))
st.selectbox('17- Actuellement, concernant votre motivation pour vos études, vous diriez que vous êtes :',('Pas motivé','Peu motivé','Assez motivé','Très motivé'))

st.header('Les pratiques pédagogiques de vos enseignants')
st.radio('18- Pensez-vous que les pratiques pédagogiques de l’ensemble de vos Professeurs en cours magistral ont globalement un impact positif sur votre motivation ?',("Oui","Non"))
st.radio('19- Pensez-vous que les pratiques pédagogiques de vos Professeurs en cours magistral contribuent à modifier vos manières d’étudier ?',['Oui','Non'])
st.radio('20- Si oui, pensez-vous que de façon générale les pratiques pédagogiques de vos professeurs vous permettent d’acquérir des manières d’étudier favorisant votre réussite aux examens ?',(("Oui","Non")))
st.write('21- Les interactions avec vos professeurs en cours magistral vous semblent-elles en règle générale :')
Su,Sa=st.columns(2)
Su.selectbox('-Suffisantes?',('Oui tout à fait','Plutôt oui','Plutôt non','Non pas du tout'))
Sa.selectbox('- Satisfaisantes ?',('Oui tout à fait','Plutôt oui','Plutôt non','Non pas du tout'))
st.selectbox("22- Diriez-vous que, de façon générale, le matériel et les supports employés par vos professeurs en cours magistral (tableau, PowerPoint, polycopiés …etc.) sont bien adaptés et facilitent vos apprentissages ?",('Oui tout à fait','Plutôt oui','Plutôt non','Non pas du tout'))
st.selectbox('24- Diriez-vous que, de façon générale, les pratiques pédagogiques employées par vos enseignants en cours magistral facilitent vos apprentissages ?',('Oui tout à fait','Plutôt oui','Plutôt non','Non pas du tout'))
st.radio('25- Pensez-vous qu’en fin de compte les pratiques pédagogiques employées par l’ensemble de vos enseignants en cours magistral soient susceptibles d’avoir un impact sur votre réussite aux examens ?',('Oui','Non'))
st.text_area('** Faites une description si vous décelez un inconvénient entre quelconques pratiques de vos professeurs et votre compétence à l’avenir :')


